kind = "problem"
service = "atcoder"
id = "abc474_a"
url = "https://atcoder.jp/contests/abc474/tasks/abc474_a"
contest_id = "abc474"
title = "A - Not X"

[template_checksums]
"main.py" = "45f3a59da4facb40b4e9292da9c0f88e37131129d9ea6a3df5c633a21c354139"
